### ISSUE TITLE
【要望】ニコ生タイピング本体のコメント入力ボックスについて

### ISSUE THREAD

**Issue by siro3** [jz5/namatyping#28]
一人でニコ生タイピングをプレイする際に下のコメントボックスに入力して遊びますが
そこのスペースが少し小さいせいで入力した文字が見づらくなってしまっています。
コメント入力の部分だけ別ウィンドウで出すようには出来ませんでしょうか？
よろしくお願いします！！！！

**Comment by esperecyan** [comment]
テストツールバーのコメント入力ボックスは、飽くまで曲データの確認などに利用するものだと認識していますが、要望の目的としては **ニコ生タイピングをライブ配信に接続せず一人でも遊べるようにしたい** ということであっていますか。

> 別ウィンドウで

これは配信接続時、スリムコメント代わりに、**https://github.com/jz5/namatyping/pull/19 のように直接メインキャプチャ範囲内に表示する** ということを想定していますか。

**Comment by siro3** [comment]
返事ありがとうございます
要望の目的は一人でも遊べるようにしたいということです
現在でも一人で遊んでいる人は何人かおりその中の一人からボックスが小さいために文字が見にくいという要望がありました。

別ウィンドウに関してですが　僕のイメージではどこかのボタンをクリックすると
メインキャプチャ範囲外に大きめのボックスが別ウィンドウで表示されてそこで歌詞を打てるようになるということを想定しています。
配信とはあまり関係ありません

**Comment by esperecyan** [comment]
なるほど、わかりました。

テストツールバーと同じ位置に、一人プレイ用ツールバーを用意して、テキスト入力欄だけを横幅いっぱいで設置するというのはどうでしょうか。

**Comment by siro3** [comment]
はい！それで大丈夫だと思います！ありがとうございます

**Comment by esperecyan** [comment]
本機能を追加した非公式β版のバイナリをアップロードしました。
https://github.com/esperecyan/namatyping/releases/tag/v2.7.0-beta.1+unofficial

**Comment by siro3** [comment]
ありがとうございます！　キャプチャ画像を見せたところ非常に喜んでいました！

**Comment by esperecyan** [comment]
動作に問題がないようであれば、このままPull Requestするので、また返信をよろしくお願いします。

**Comment by jz5** [comment]
PRしてください
